# Generated by Django 5.2.5 on 2025-08-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_registromaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['id']},
        ),
    ]
