# Generated by Django 5.2.5 on 2025-08-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('materiales', '0003_alter_material_options_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='materiales.proveedor'),
        ),
    ]
